version: '3.7'
services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql #volume criado
     environment: #variaveis do container
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     depends_on: #para subir esse serviço é necessário subir o DB primeiro
       - db
     image: wordpress:latest
     ports:
       - "8000:80"
     environment: #variaveis do container
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
volumes: #declaração do volume
  db_data:
